{{- $httpRoute := .Values.otelCollectorHTTPRoute }}
{{- if and $httpRoute $httpRoute.enabled }}
{{- $httpRoutes := list $httpRoute }}
{{- if $httpRoute.additionalHTTPRoutes }}
{{-   $httpRoutes = concat $httpRoutes $httpRoute.additionalHTTPRoutes -}}
{{- end }}
{{- range $httpRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  {{- if .name }}
  name: otel-collector-{{ .name | lower }}
  {{- else }}
  name: otel-collector
  {{- end }}
  labels:
    {{- include "otel-demo.labels" $ | nindent 4 }}
  {{- if .annotations }}
  annotations:
    {{ toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- range .parentRefs }}
    - name: {{ .name }}
      {{- with .namespace }}
      namespace: {{ . }}
      {{- end }}
      {{- with .sectionName }}
      sectionName: {{ . }}
      {{- end }}
    {{- end }}
  {{- if .hostnames }}
  hostnames:
    {{- range .hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .rules }}
    - matches:
        {{- range .matches }}
        - path:
            type: {{ .path.type }}
            value: {{ .path.value }}
        {{- end }}
      {{- if .rewritePath }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: {{ .rewritePath }}
      {{- end }}
      backendRefs:
        - name: otel-collector
          port: {{ .port }}
    {{- end }}
{{- end}}
{{- end}}
