opentelemetry-collector:
  config:
    exporters:
      otlp/observability-backend:
        endpoint: "my-observability-endpoint:4317"
  presets:
    logsCollection:
      enabled: false
      storeCheckpoints: false
    hostMetrics:
      enabled: false
    kubeletMetrics:
      enabled: false
    clusterMetrics:
      enabled: false
