apiVersion: v2
type: application
name: otel-demo-fork
version: 0.11.12
description: Helm chart for ryanfaircloth/opentelemetry-demo (fork of the OpenTelemetry Demo)
home: https://opentelemetry.io/
sources:
  - https://github.com/ryanfaircloth/opentelemetry-demo
  - https://github.com/open-telemetry/opentelemetry-helm-charts
maintainers:
  - name: dmitryax
  - name: jaronoff97
  - name: julianocosta89
  - name: puckpuck
  - name: tylerhelmuth
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
appVersion: 2.2.0
dependencies:
  - name: opentelemetry-collector
    version: 0.153.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
