<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    <ProtosDir>$(ProjectDir)..\pb</ProtosDir>
  </PropertyGroup>

  <PropertyGroup Condition="!Exists('$(ProtosDir)')">
    <ProtosDir>$(ProjectDir)..\..\..\pb</ProtosDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.AspNetCore.HealthChecks" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="OpenFeature.Providers.Flagd" />
    <PackageReference Include="OpenFeature" />
    <PackageReference Include="OpenFeature.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="$(ProtosDir)\**\*.proto" GrpcServices="Both" />
  </ItemGroup>
</Project>
